-- Expose admin menus to anonymous for development convenience
INSERT IGNORE INTO LETTNMENUCREATDTLS (MENU_NO, AUTHOR_CODE, MAPNG_CREAT_ID)
SELECT MENU_NO, 'ROLE_ANONYMOUS', NULL
  FROM LETTNMENUINFO
 WHERE UPPER_MENU_NO IN (6000000)
    OR MENU_NO BETWEEN 6010000 AND 6020400;

