-- Hide admin menus from anonymous (revert dev exposure)
DELETE MC
  FROM LETTNMENUCREATDTLS MC
  JOIN LETTNMENUINFO MI ON MC.MENU_NO = MI.MENU_NO
 WHERE MC.AUTHOR_CODE = 'ROLE_ANONYMOUS'
   AND (MI.UPPER_MENU_NO IN (6000000)
        OR MI.MENU_NO BETWEEN 6010000 AND 6020400);

