-- Ensure cross-user master view exists with MySQL syntax
CREATE OR REPLACE VIEW COMVNUSERMASTER (
  ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES,
  USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID
) AS
SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES,
       MBER_EMAIL_ADRES, '' AS GROUP_ID, 'GNR' AS USER_SE, '' AS ORGNZT_ID
  FROM LETTNGNRLMBER
UNION ALL
SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES,
       EMAIL_ADRES, GROUP_ID, 'USR' AS USER_SE, ORGNZT_ID
  FROM LETTNEMPLYRINFO
UNION ALL
SELECT ESNTL_ID, ENTRPRS_MBER_ID, ENTRPRS_MBER_PASSWORD, CMPNY_NM, ZIP, ADRES,
       APPLCNT_EMAIL_ADRES, '' AS GROUP_ID, 'ENT' AS USER_SE, '' AS ORGNZT_ID
  FROM LETTNENTRPRSMBER;

