-- Basic DB sanity: current DB and core tables/views
SELECT DATABASE() AS current_db;

-- Key tables should exist and have rows after seed
SELECT 'LETTNBBSMASTER' AS table_name, COUNT(*) AS cnt FROM LETTNBBSMASTER;
SELECT 'LETTNBBS' AS table_name, COUNT(*) AS cnt FROM LETTNBBS;
SELECT 'LETTCCMMNCLCODE' AS table_name, COUNT(*) AS cnt FROM LETTCCMMNCLCODE;
SELECT 'LETTCCMMNCODE' AS table_name, COUNT(*) AS cnt FROM LETTCCMMNCODE;
SELECT 'LETTNFAQINFO' AS table_name, COUNT(*) AS cnt FROM LETTNFAQINFO;
SELECT 'LETTNSTPLATINFO' AS table_name, COUNT(*) AS cnt FROM LETTNSTPLATINFO;

-- Views present?
SHOW FULL TABLES WHERE Table_type = 'VIEW';

-- Check the COMVNUSERMASTER view DDL if present
SHOW CREATE VIEW COMVNUSERMASTER;

-- Admin/menus: core counts and quick sanity
SELECT 'LETTNMENUINFO' AS table_name, COUNT(*) AS cnt FROM LETTNMENUINFO;
SELECT 'LETTNMENUCREATDTLS' AS table_name, COUNT(*) AS cnt FROM LETTNMENUCREATDTLS;
SELECT 'LETTNPROGRMLIST' AS table_name, COUNT(*) AS cnt FROM LETTNPROGRMLIST;
SELECT 'LETTNROLEINFO' AS table_name, COUNT(*) AS cnt FROM LETTNROLEINFO;
SELECT 'LETTNAUTHORROLERELATE' AS table_name, COUNT(*) AS cnt FROM LETTNAUTHORROLERELATE;
SELECT 'LETTNBBSMASTER' AS table_name, COUNT(*) AS cnt FROM LETTNBBSMASTER;
SELECT 'LETTNBBSUSE' AS table_name, COUNT(*) AS cnt FROM LETTNBBSUSE;

-- Admin user presence and status
SELECT MBER_ID, MBER_NM, MBER_STTUS, ESNTL_ID FROM LETTNGNRLMBER WHERE MBER_ID IN ('admin','user1');

-- Top menus visible to anonymous (for header/left rendering)
SELECT B.MENU_NO, B.MENU_NM, B.MENU_ORDR, B.UPPER_MENU_NO, B.PROGRM_FILE_NM
  FROM LETTNMENUCREATDTLS A JOIN LETTNMENUINFO B ON A.MENU_NO = B.MENU_NO
 WHERE B.UPPER_MENU_NO = 0 AND A.AUTHOR_CODE = 'ROLE_ANONYMOUS'
 ORDER BY B.MENU_ORDR
 LIMIT 20;

-- Any admin menus mapped? (if ROLE_ADMIN exists)
SELECT B.MENU_NO, B.MENU_NM, B.MENU_ORDR, B.UPPER_MENU_NO, B.PROGRM_FILE_NM
  FROM LETTNMENUCREATDTLS A JOIN LETTNMENUINFO B ON A.MENU_NO = B.MENU_NO
 WHERE A.AUTHOR_CODE = 'ROLE_ADMIN'
 ORDER BY B.MENU_ORDR
 LIMIT 20;
